{"version":3,"file":"index.spec.js","sourceRoot":"","sources":["../src/index.spec.ts"],"names":[],"mappings":";AAAA,IAAO,IAAI,WAAW,WAAW,CAAC,CAAA;AAClC,IAAO,cAAc,WAAW,SAAS,CAAC,CAAA;AAE1C,IAAI,CAAC,kBAAkB,EAAE,UAAA,CAAC;IACxB,IAAM,SAAS,GAAG,cAAc,CAAC,WAAW,CAAC,CAAA;IAC7C,IAAM,YAAY,GAAG,cAAc,CAAC,cAAc,EAAE,SAAS,CAAC,CAAA;IAE9D,CAAC,CAAC,IAAI,CAAC,kBAAkB,EAAE,UAAA,CAAC;QAC1B,IAAM,KAAK,GAAG,IAAI,KAAK,CAAC,OAAO,CAAC,CAAA;QAChC,IAAM,KAAK,GAAG,IAAI,SAAS,CAAC,eAAe,EAAE,KAAK,CAAC,CAAA;QACnD,IAAM,KAAK,GAAG,IAAI,YAAY,CAAC,UAAU,EAAE,KAAK,CAAC,CAAA;QAEjD,CAAC,CAAC,KAAK,CAAC,KAAK,CAAC,KAAK,EAAE,KAAK,CAAC,CAAA;QAC3B,CAAC,CAAC,KAAK,CAAC,KAAK,CAAC,QAAQ,EAAE,EAAE,mDAAmD,CAAC,CAAA;QAC9E,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,KAAK,CAAC,CAAA;QAC5B,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,cAAc,CAAC,SAAS,CAAC,CAAA;QAC/C,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,SAAS,CAAC,CAAA;QAEhC,CAAC,CAAC,KAAK,CAAC,KAAK,CAAC,KAAK,EAAE,KAAK,CAAC,CAAA;QAC3B,CAAC,CAAC,KAAK,CAAC,KAAK,CAAC,QAAQ,EAAE,EAAE,sFAAsF,CAAC,CAAA;QACjH,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,KAAK,CAAC,CAAA;QAC5B,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,cAAc,CAAC,SAAS,CAAC,CAAA;QAC/C,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,SAAS,CAAC,CAAA;QAChC,CAAC,CAAC,EAAE,CAAC,KAAK,YAAY,YAAY,CAAC,CAAA;QAEnC,CAAC,CAAC,GAAG,EAAE,CAAA;IACT,CAAC,CAAC,CAAA;AACJ,CAAC,CAAC,CAAA","sourcesContent":["import test = require('blue-tape')\nimport makeErrorCause = require('./index')\n\ntest('make error cause', t => {\n  const TestError = makeErrorCause('TestError')\n  const SubTestError = makeErrorCause('SubTestError', TestError)\n\n  t.test('render the cause', t => {\n    const cause = new Error('boom!')\n    const error = new TestError('something bad', cause)\n    const again = new SubTestError('more bad', error)\n\n    t.equal(error.cause, cause)\n    t.equal(error.toString(), 'TestError: something bad\\nCaused by: Error: boom!')\n    t.ok(error instanceof Error)\n    t.ok(error instanceof makeErrorCause.BaseError)\n    t.ok(error instanceof TestError)\n\n    t.equal(again.cause, error)\n    t.equal(again.toString(), 'SubTestError: more bad\\nCaused by: TestError: something bad\\nCaused by: Error: boom!')\n    t.ok(again instanceof Error)\n    t.ok(again instanceof makeErrorCause.BaseError)\n    t.ok(again instanceof TestError)\n    t.ok(again instanceof SubTestError)\n\n    t.end()\n  })\n})\n"]}